name: Docker CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout source
              uses: actions/checkout@v2

            - name: Log in to Github Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Set up Docker
              uses: docker/setup-buildx-action@v3
            
            - name: Build Docker image
              run: docker build -t ghcr.io/${{ github.repository }}:latest .
      
            - name: Push Docker image
              run: docker push ghcr.io/${{ github.repository }}:latest

            - name: Lint check (optional)
              run: echo "No linting for now. Add ESLint later."